train_file:  'data/industry_small/train.jsonl'
val_file: 'data/industry_small/dev.jsonl'
test_file: 'data/industry_small/test.jsonl'
pnum: 1
train_nnum: 19
queue_size: 65536
momentum: 0.995
embed_dim: 256
warm_up: True
optimizer: {opt: adamW, lr: 8e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 8e-5, epochs: 50, min_lr: 1e-6,
            decay_rate: 1, warmup_lr: 8e-5, warmup_epochs: 1,
            cooldown_epochs: 0}